version: '2'

services:
  etcd:
    image: bitnami/etcd:3
    ports:
      - 12379:2379
      - 12380:2380
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://127.0.0.1:12379
    volumes:
      - E:/volumes/etcd/data:/bitnami
  
  # etcd-manage:
    # image: shiguanghuxian/etcd-manage
    # volumes:
      # - E:/volumes/etcd/config/cfg.toml:/app/config/cfg.toml
      # - E:/volumes/etcd/logs:/app/logs
    # ports:
      # - 10280:10280
      
volumes:
  etcd_data:
    driver: local
