version: '3.5'

services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.5.0
    environment:
      - -strict.perms=false
    volumes:
      - /opt/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
  

