apisix:
  node_listen: 9080
  enable_ipv6: false

  allow_admin:
    - 0.0.0.0/0

  admin_key:
    - name: "admin"
      key: edd1c9f034335f136f87ad84b625c8f2
      role: admin

    - name: "viewer"
      key: 4054f7cf07e344346cd3f287985e76a3
      role: viewer

etcd:
  host:
    - "http://etcd:12379"
  prefix: "/apisix"
  timeout: 30
