version: '3.5'

services:
  grafana:
    image: grafana/grafana:7.3.6
    container_name: grafana
    user: root
    ports:
      - 13000:3000
    volumes:
      - ./config/dashboards:/var/lib/grafana/dashboards
      - ./config/datasources:/etc/grafana/datasources
      - ./config/plugins:/var/lib/grafana/plugins
      - ./data:/var/lib/grafana

networks:
  default:
    external: true
    name: localnet