version: '3'

services:
  mongo:
    image: mongo:4.2.1
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    # volumes:
    #   - E:/volumes/mongo/data:/data/db

  mongo-express:
    image: mongo-express:0.49
    restart: always
    ports:
      - 18081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456