version: '3.5'

services:
  apisix:
    image: apache/apisix
    restart: always
    container_name: apisix
    ports:
      - "19080:9080/tcp"
      - "19443:9443/tcp"
    depends_on:
      - etcd
    volumes:
      - ./apisix_log:/usr/local/apisix/logs
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
  
  apisix-dashboard:
    image: docker.flexem.com/test/apisix-dashboard:2.2
    restart: always
    container_name: apisix-dashboard
    ports:
      - "19100:9000"
    depends_on:
      - etcd
    volumes:
      - ./apisix_dashboard_log:/usr/local/apisix/logs
      - ./apisix_conf/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml:ro

  etcd:
    image: bitnami/etcd:3.4.9
    user: root
    restart: always
    volumes:
      - ./etcd_data:/etcd_data
    environment:
      ETCD_DATA_DIR: /etcd_data
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:12379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:12379"
    ports:
      - "12379:2379/tcp"

networks:
  default:
    external: true
    name: localnet