version: '3.5'

services:
  web:
    image: nginx:1.19
    ports:
     - "80:80"
    environment:
     - NGINX_HOST=wwb.com
     - NGINX_PORT=80
    volumes:
     - /opt/nginx/templates:/etc/nginx/templates
      
