version: '3.5'

services:
  scylla-0:
    image: scylladb/scylla:3.1.1
    restart: always
    ports:
      - 19042:9042
    container_name: scylla-0
    command: --cluster-name=TestCluster --endpoint-snitch GossipingPropertyFileSnitch
    volumes:
      - /opt/scylladb/data0:/var/lib/scylla
      - /opt/scylladb/cassandra-rackdc.properties:/etc/scylla/cassandra-rackdc.properties
  scylla-1:
    image: scylladb/scylla:3.1.1
    restart: always
    ports:
      - 29042:9042
    container_name: scylla-1
    command: --seeds=scylla-0 --cluster-name=TestCluster --endpoint-snitch GossipingPropertyFileSnitch
    volumes:
      - /opt/scylladb/data1:/var/lib/scylla
      - /opt/scylladb/cassandra-rackdc.properties:/etc/scylla/cassandra-rackdc.properties
  scylla-2:
    image: scylladb/scylla:3.1.1
    restart: always
    ports:
      - 39042:9042
    container_name: scylla-2
    command: --seeds=scylla-0 --cluster-name=TestCluster --endpoint-snitch GossipingPropertyFileSnitch
    volumes:
      - /opt/scylladb/data2:/var/lib/scylla
      - /opt/scylladb/cassandra-rackdc.properties:/etc/scylla/cassandra-rackdc.properties
