version: '3.5'

services:
  standalone:
    image: apachepulsar/pulsar:2.8.0
    container_name: pulsar
    restart: always
    expose:
      - 8080
      - 6650
    environment:
      - BOOKIE_MEM=" -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py conf/standalone.conf
      && bin/pulsar standalone --advertised-address standalone"
    volumes: 
      - ./pulsardata:/pulsar/data
      - ./pulsarconf:/pulsar/conf

  dashboard:
    image: apachepulsar/pulsar-dashboard:2.8.0
    container_name: pulsar-dashboard
    restart: always
    depends_on:
      - standalone
    ports:
      - 10180:80
    environment:
      - SERVICE_URL=http://standalone:8080

networks:
  default:
    external: true
    name: localnet